# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20170329_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='latlon',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='initiative',
            old_name='latlon',
            new_name='position',
        ),
    ]
