# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20170401_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='initiative',
            name='address',
            field=models.CharField(help_text='Dirección de la iniciativa', max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='district',
            field=models.CharField(help_text='¿En qué barrio de la ciudad se sitúa la iniciativa?', max_length=200, null=True, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='agent',
            field=models.CharField(choices=[('IM', 'Iniciativas municipales / Gobierno'), ('UO', 'Universidades / ONG / Fundaciones'), ('OI', 'Organismos internacionales'), ('ES', 'Empresa social / Startup'), ('IC', 'Iniciativa ciudadana'), ('JA', 'Juntas / Asociaciones de vecinos')], default='IM', help_text='El tipo de agente involucrado en la iniciativa', max_length=2, verbose_name='tipo de agente'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='name',
            field=models.CharField(help_text='¿Cuál es el nombre de tu iniciativa?', max_length=200, null=True, verbose_name='Nombre de la iniciativa'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='space',
            field=models.CharField(choices=[('CC', 'Centro cultural/comunitario'), ('EI', 'Efímero e itinerante'), ('IT', 'Intercambio / Trueque'), ('DI', 'Digital'), ('EA', 'Encuentros / Acciones'), ('EP', 'Escuelas populares'), ('HU', 'Huerto urbano/rural'), ('IU', 'Intervenciones urbanas'), ('MC', 'Medios de comunicación comunitaria'), ('MS', 'Mercado social / Comercios'), ('SE', 'Solares / Espacios recuperados'), ('EM', 'Labs / Colaborativos / Maker')], default='CC', help_text='El tipo de espacio asociado a la iniciativa', max_length=2, verbose_name='Tipo de espacio'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='topic',
            field=models.CharField(choices=[('DC', 'Desarrollo comunitario'), ('AU', 'Arte urbano'), ('CL', 'Cultura libre'), ('DS', 'Deporte / Salud / Cuidados'), ('ID', 'Igualdad / Derechos / Memoria'), ('EC', 'Ecología / Consumo'), ('OE', 'Otras economías'), ('EE', 'Educación expandida'), ('CT', 'Ciencia / Tecnología'), ('MS', 'Movilidad sostenible'), ('PG', 'Política y gobernanza'), ('UP', 'Urbanismo / Patrimonio'), ('PC', 'Periodismo comunitario')], default='DC', help_text='El tema de la iniciativa', max_length=2, verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='twitter',
            field=models.CharField(blank=True, help_text='Si tienes una cuenta de Twitter, pon aquí el nombre del usuario sin la @ inicial.', max_length=128, null=True, verbose_name='Twitter'),
        ),
    ]
