# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20170425_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='user',
        ),
    ]
