# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_initiative_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='video',
            field=models.CharField(help_text='Inserta la url de un video de Youtube o Vimeo', max_length=200, null=True, verbose_name='Video'),
        ),
    ]
