# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_initiative_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(help_text='Ciudad donde se encuentra la iniciativa. Si no la encuentras en la lista puedes añadir una nueva.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.City', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube una imagen representativa del evento', upload_to='images/initiatives/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.CharField(help_text='Inserta la url de un video de Youtube o Vimeo', max_length=200, null=True, verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, help_text='Especifica opcionalmente una web para conocer mejor el evento.', null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('AU', 'Audiovisual'), ('CU', 'Curso / Convocatoria'), ('DI', 'Digital'), ('EN', 'Encuentro'), ('EV', 'Evento'), ('EX', 'Exposicion'), ('FI', 'Fiesta / Concierto'), ('PU', 'Publicación'), ('TA', 'Taller')], default='AU', help_text='El tipo de actividad que quieres organizar', max_length=2, verbose_name='Tipo de actividad'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='¿Qué día se celebra el evento?', verbose_name='Fecha del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Describe el evento.', null=True, verbose_name='Descripción de la iniciativa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(help_text='¿A qué hora se celebra el evento?', verbose_name='Hora del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.CharField(choices=[('DC', 'Desarrollo comunitario'), ('AU', 'Arte urbano'), ('CL', 'Cultura libre'), ('DS', 'Deporte / Salud / Cuidados'), ('ID', 'Igualdad / Derechos / Memoria'), ('EC', 'Ecología / Consumo'), ('OE', 'Otras economías'), ('EE', 'Educación expandida'), ('CT', 'Ciencia / Tecnología'), ('MS', 'Movilidad sostenible'), ('PG', 'Política y gobernanza'), ('UP', 'Urbanismo / Patrimonio'), ('PC', 'Periodismo comunitario')], default='DC', help_text='El tema de la actividad', max_length=2, verbose_name='Temática del evento'),
        ),
    ]
