# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20170428_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, help_text='Especifica opcionalmente un enlace para conocer mejor el evento.', null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='city',
            field=models.ForeignKey(help_text='Ciudad donde se encuentra la iniciativa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.City', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='district',
            field=models.CharField(blank=True, help_text='¿En qué barrio de la ciudad se sitúa la iniciativa?', max_length=200, null=True, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='facebook',
            field=models.URLField(blank=True, help_text='Si tienes un perfil de Facebook pon aquí el enlace completo a la misma.', null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='video',
            field=models.CharField(blank=True, help_text='Inserta la url de un video de Youtube o Vimeo', max_length=200, null=True, verbose_name='Video'),
        ),
    ]
