# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20170508_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='agent',
            field=models.CharField(choices=[('IM', 'Iniciativas municipales / Gobierno'), ('UO', 'Universidades / ONG / Fundaciones'), ('OI', 'Organismos internacionales'), ('ES', 'Empresa social / Startup'), ('IC', 'Iniciativa ciudadana'), ('JA', 'Juntas / Asociaciones de vecinos'), ('CC', 'Conquistas ciudadanas del pasado')], default='IM', help_text='El tipo de agente involucrado en la actividad', max_length=2, verbose_name='tipo de agente'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='agent',
            field=models.CharField(choices=[('IM', 'Iniciativas municipales / Gobierno'), ('UO', 'Universidades / ONG / Fundaciones'), ('OI', 'Organismos internacionales'), ('ES', 'Empresa social / Startup'), ('IC', 'Iniciativa ciudadana'), ('JA', 'Juntas / Asociaciones de vecinos'), ('CC', 'Conquistas ciudadanas del pasado')], default='IM', help_text='El tipo de agente involucrado en la iniciativa', max_length=2, verbose_name='tipo de agente'),
        ),
    ]
