# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_auto_20170606_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False, help_text='Indica si es un evento destacado', verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='featured',
            field=models.BooleanField(default=False, help_text='Indica si es una iniciativa destacada', verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Describe el evento.', null=True, verbose_name='Describe el evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='initiative',
            field=models.ForeignKey(blank=True, help_text='¿Qué iniciativa organiza el evento?', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Initiative', verbose_name='Iniciativa que organiza la actividad'),
        ),
    ]
