# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 14:20
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_auto_20170630_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_test',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
