# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_auto_20170703_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_test',
            new_name='country',
        ),
    ]
