# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20170703_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
