# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_event_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('DI', 'Diaria'), ('SE', 'Semanal'), ('QU', 'Quincenal'), ('ME', 'Mensual'), ('AN', 'Anual')], help_text='Especifica, en ese caso, la periodicidad del evento.', max_length=2, null=True, verbose_name='Periodicidad'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='space',
            field=models.CharField(choices=[('CC', 'Centro cultural / comunitario'), ('EI', 'Efímero e itinerante'), ('IT', 'Intercambio / Trueque'), ('DI', 'Digital'), ('EA', 'Encuentros / Acciones'), ('EP', 'Escuelas populares'), ('HU', 'Huerto urbano/rural'), ('IU', 'Intervenciones urbanas'), ('MC', 'Medios de comunicación comunitaria'), ('MS', 'Mercado social / Comercios'), ('SE', 'Solares / Espacios recuperados'), ('EM', 'Labs / Colaborativos / Maker')], default='CC', help_text='El tipo de espacio asociado a la iniciativa', max_length=2, verbose_name='Tipo de espacio'),
        ),
    ]
