# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_auto_20170908_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='email',
            field=models.EmailField(help_text='Especifica un correo de contacto para la iniciativa.', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
    ]
