# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 12:21
from __future__ import unicode_literals

import apps.models.utils
import apps.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_auto_20170924_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube una imagen representativa del evento haciendo click en la imagen inferior. La imagen ha de tener ancho mínimo de 300 píxeles y máximo de 1920, y altura mínima de 300 píxeles y máxima de 1280. Formatos permitidos: PNG, JPG, JPEG.', upload_to=apps.models.utils.RenameCivicsImage('images/events/'), validators=[apps.models.validators.ImageSizeValidator({'max_height': 1280, 'max_width': 1920, 'min_height': 300, 'min_width': 600}), apps.models.validators.ImageTypeValidator(['jpeg', 'png'])], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube una imagen representativa de la iniciativa haciendo click en la imagen inferior. La imagen ha de tener ancho mínimo de 300 píxeles y máximo de 1920, y altura mínima de 300 píxeles y máxima de 1280. Formatos permitidos: PNG, JPG, JPEG.', upload_to=apps.models.utils.RenameCivicsImage('images/initiatives/'), validators=[apps.models.validators.ImageSizeValidator({'max_height': 1280, 'max_width': 1920, 'min_height': 300, 'min_width': 600}), apps.models.validators.ImageTypeValidator(['jpeg', 'png'])], verbose_name='Imagen'),
        ),
    ]
