# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_auto_20170924_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
