# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_auto_20170927_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
