# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-15 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0034_auto_20180110_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(help_text='Especifica el nombre de la ciudad en inglés.', max_length=200, null=True, verbose_name='Nombre de la ciudad (EN)'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_pt',
            field=models.CharField(help_text='Especifica el nombre de la ciudad en portugúes.', max_length=200, null=True, verbose_name='Nombre de la ciudad (PT)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='agent',
            field=models.CharField(choices=[('IM', 'Iniciativas municipales / Gobierno'), ('UO', 'Universidades / ONG / Fundaciones'), ('OI', 'Organismos internacionales'), ('ES', 'Empresa social / Startup'), ('IC', 'Iniciativa ciudadana'), ('JA', 'Juntas / Asociaciones de vecinos'), ('CC', 'Iniciativas ciudadanas inactivas')], default='IM', help_text='El tipo de agente involucrado en la actividad', max_length=2, verbose_name='tipo de agente'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='agent',
            field=models.CharField(choices=[('IM', 'Iniciativas municipales / Gobierno'), ('UO', 'Universidades / ONG / Fundaciones'), ('OI', 'Organismos internacionales'), ('ES', 'Empresa social / Startup'), ('IC', 'Iniciativa ciudadana'), ('JA', 'Juntas / Asociaciones de vecinos'), ('CC', 'Iniciativas ciudadanas inactivas')], default='IM', help_text='El tipo de agente involucrado en la iniciativa', max_length=2, verbose_name='tipo de agente'),
        ),
    ]
