# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0035_auto_20180115_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Especifica el nombre de la ciudad en español.', max_length=200, null=True, verbose_name='Nombre de la ciudad'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(help_text='Especifica el nombre de la ciudad en inglés si es distinto al nombre español.', max_length=200, null=True, verbose_name='Nombre de la ciudad (EN)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_pt',
            field=models.CharField(help_text='Especifica el nombre de la ciudad en portugúes si es distinto al nombre español.', max_length=200, null=True, verbose_name='Nombre de la ciudad (PT)'),
        ),
    ]
