# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-25 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0039_auto_20180924_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre del ODS')),
            ],
        ),
        migrations.AlterField(
            model_name='initiative',
            name='main_ods',
            field=models.ForeignKey(blank=True, help_text='Indícanos que Objetivo de Desarrollo Sostenible (ODS) crees que cumple o trabaja principalmente tu iniciativa.', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ODS', verbose_name='ODS principal'),
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='other_ods',
        ),
        migrations.AddField(
            model_name='initiative',
            name='other_ods',
            field=models.ManyToManyField(blank=True, help_text='Indícanos otros Objetivos de Desarrollo Sostenible (ODS) con los que también trabaja tu iniciativa (máximo 3).', related_name='initiatives', to='models.ODS', verbose_name='Otros ODS'),
        ),
    ]
