# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0041_auto_20180925_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ods',
            options={'ordering': ['order'], 'verbose_name': 'ODS', 'verbose_name_plural': 'ODS'},
        ),
        migrations.AddField(
            model_name='ods',
            name='category',
            field=models.CharField(choices=[('1', 'Fin de la pobreza'), ('2', 'Hambre cero'), ('3', 'Salud y bienestar'), ('4', 'Educación de calidad'), ('5', 'Igualdad de género'), ('6', 'Agua limpia y saneamiento'), ('7', 'Energía asequible y no contaminante'), ('8', 'Trabajo decente y crecimiento económico'), ('9', 'Industria, innovación e infraestructura'), ('10', 'Reducción de las desigualdades'), ('11', 'Ciudades y comunidades sostenibles'), ('12', 'Producción y consumo responsables'), ('13', 'Acción por el clima'), ('14', 'Vida submarina'), ('15', 'Vida de ecosistemas terrestres'), ('16', 'Paz, justicia e instituciones sólidas'), ('17', 'Alianzas para lograr los objetivos')], default=1, max_length=2, verbose_name='Objetivo de desarrollo sostenible'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='main_ods',
            field=models.ForeignKey(blank=True, help_text='Indícanos que Objetivo de Desarrollo Sostenible (ODS) crees que cumple o trabaja principalmente tu iniciativa.', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ODS', verbose_name='Objetivo de desarrollo sostenible principal'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='other_ods',
            field=models.ManyToManyField(blank=True, help_text='Indícanos otros Objetivos de Desarrollo Sostenible (ODS) con los que también trabaja tu iniciativa (máximo 3). Puedes deseleccionar y hacer selecciones múltiples usando el ratón con la tecla Ctrl pulsada (Command en MAC)', related_name='initiatives', to='models.ODS', verbose_name='Otros ODS'),
        ),
    ]
