# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-26 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0042_auto_20180926_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ods',
            name='name',
        ),
    ]
