# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-17 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0044_initiative_initiatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='initiatives',
            field=models.ManyToManyField(blank=True, related_name='_initiative_initiatives_+', to='models.Initiative', verbose_name='Relaciones'),
        ),
    ]
