# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-24 21:01
from __future__ import unicode_literals

import apps.models.utils
import apps.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0045_auto_20181017_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nombre del recurso')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nombre del recurso en inglés')),
                ('name_pt', models.CharField(max_length=200, null=True, verbose_name='Nombre del recurso en portugués')),
                ('category', models.CharField(choices=[('0', 'Guías'), ('1', 'Mapas'), ('2', 'Señalética urbana'), ('3', 'Forks de civics'), ('4', 'Otras plataformas')], default='0', max_length=2, verbose_name='Tipo de recurso')),
                ('image', models.ImageField(blank=True, upload_to=apps.models.utils.RenameCivicsImage('images/resources/'), validators=[apps.models.validators.ImageSizeValidator({'max_height': 1280, 'max_width': 1920, 'min_height': 300, 'min_width': 600}), apps.models.validators.ImageTypeValidator(['jpeg', 'png'])], verbose_name='Imagen')),
                ('file', models.FileField(blank=True, upload_to=apps.models.utils.RenameCivicsImage('files/resources/'), verbose_name='Archivo')),
                ('summary', models.TextField(null=True, verbose_name='Descripción corta del recurso')),
                ('summary_en', models.TextField(null=True, verbose_name='Descripción corta del recurso [inglés]')),
                ('summary_pt', models.TextField(null=True, verbose_name='Descripción corta del recurso [portugués]')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube una imagen representativa del evento haciendo click en la imagen inferior. La imagen ha de tener ancho mínimo de 600 píxeles y máximo de 1920, y altura mínima de 300 píxeles y máxima de 1280. Formatos permitidos: PNG, JPG, JPEG.', upload_to=apps.models.utils.RenameCivicsImage('images/events/'), validators=[apps.models.validators.ImageSizeValidator({'max_height': 1280, 'max_width': 1920, 'min_height': 300, 'min_width': 600}), apps.models.validators.ImageTypeValidator(['jpeg', 'png'])], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.CharField(choices=[('DC', 'Desarrollo comunitario'), ('AU', 'Arte urbano'), ('CL', 'Cultura libre'), ('DS', 'Deporte / Salud / Cuidados'), ('ID', 'Igualdad / Derechos / Memoria'), ('EC', 'Ecología / Consumo'), ('OE', 'Otras economías'), ('EE', 'Educación expandida'), ('CT', 'Ciencia / Tecnología'), ('MS', 'Movilidad sostenible'), ('PG', 'Política y gobernanza'), ('UP', 'Urbanismo / Patrimonio'), ('PC', 'Periodismo comunitario'), ('IN', 'Infancia'), ('DI', 'Digitalización / Datos Abiertos'), ('FE', 'Feminismos')], default='DC', help_text='El tema de la actividad', max_length=2, verbose_name='Temática del evento'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube una imagen representativa de la iniciativa haciendo click en la imagen inferior. La imagen ha de tener ancho mínimo de 600 píxeles y máximo de 1920, y altura mínima de 300 píxeles y máxima de 1280. Formatos permitidos: PNG, JPG, JPEG.', upload_to=apps.models.utils.RenameCivicsImage('images/initiatives/'), validators=[apps.models.validators.ImageSizeValidator({'max_height': 1280, 'max_width': 1920, 'min_height': 300, 'min_width': 600}), apps.models.validators.ImageTypeValidator(['jpeg', 'png'])], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='topic',
            field=models.CharField(choices=[('DC', 'Desarrollo comunitario'), ('AU', 'Arte urbano'), ('CL', 'Cultura libre'), ('DS', 'Deporte / Salud / Cuidados'), ('ID', 'Igualdad / Derechos / Memoria'), ('EC', 'Ecología / Consumo'), ('OE', 'Otras economías'), ('EE', 'Educación expandida'), ('CT', 'Ciencia / Tecnología'), ('MS', 'Movilidad sostenible'), ('PG', 'Política y gobernanza'), ('UP', 'Urbanismo / Patrimonio'), ('PC', 'Periodismo comunitario'), ('IN', 'Infancia'), ('DI', 'Digitalización / Datos Abiertos'), ('FE', 'Feminismos')], default='DC', help_text='El tema de la iniciativa', max_length=2, verbose_name='Tema'),
        ),
    ]
