# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-24 21:34
from __future__ import unicode_literals

import apps.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0046_auto_20190624_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, help_text='Si el recurso es un site externo puedes indicar la url aquí.', verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, upload_to='files/resources', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/resources', validators=[apps.models.validators.ImageSizeValidator({'max_height': 1280, 'max_width': 1920, 'min_height': 300, 'min_width': 600}), apps.models.validators.ImageTypeValidator(['jpeg', 'png'])], verbose_name='Imagen'),
        ),
    ]
