# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-25 18:16
from __future__ import unicode_literals

import apps.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0047_auto_20190624_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='file',
            field=models.FileField(blank=True, help_text='Puedes usar este campo para subir algún documento que explique mejor tu iniciativa. Sólo admite formato PDF.', upload_to='files/initiatives', validators=[apps.models.validators.AttachedFileValidator()], verbose_name='Archivo adjunto'),
        ),
    ]
